import type { Metadata } from "next"

import "./globals.css"

import "@mantine/core/styles.layer.css"
import { Roboto } from "next/font/google"

import { ColorSchemeScript, Flex, MantineProvider } from "@mantine/core"
import Navbar from "./components/layout/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
import local from "next/font/local"

const Grotesk = local({
  src: [
    {
      path: "../../public/fonts/Oldschool-Grotesk-Bold.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/Oldschool-Grotesk-ExtraBold.otf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Oldschool-Grotesk-Heavy.otf",
      weight: "800",
    },
  ],
  variable: "--font-Grotesk",
})
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-roboto",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${roboto.variable} ${Grotesk.variable}  bg-[#130F18] text-white`}>
        <MantineProvider>
          <Navbar />
          <Flex
            className="z-10 border-2 border-blue-800"
            direction="column"
            w="100%"
            style={{
              minHeight: "calc(100vh - 60px)",
            }}
            mt="60px">
            {children}
          </Flex>
        </MantineProvider>
      </body>
    </html>
  )
}
