import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import "@mantine/core/styles.layer.css"
const inter = Inter({ subsets: ["latin"] })

import { ColorSchemeScript, Flex, MantineProvider } from "@mantine/core"
import Navbar from "./components/layout/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Navbar />
          <Flex direction="column">{children}</Flex>
        </MantineProvider>
      </body>
    </html>
  )
}
